Update UI filtering
eger-geger/nunit-html-report pull request #2
Opened 2016-11-24 12:36 UTC by AlexGalchenko

2016-11-24 13:06 UTC, eger-geger requested changes
Please take a look on comments before merge

2016-11-24 13:06 UTC, eger-geger commented on templates/default/views/DashboardView.html
> +               <label for="excludeFilter"><input type="checkbox" id="excludeFilter" ng-model="excludeFilter" ng-checked="excludeFilter"><code> Exclude</code></label>
According to [angular](https://docs.angularjs.org/api/ng/directive/ngChecked) _ng-checked_ should not be used together with _ng-model_

2016-11-24 13:06 UTC, eger-geger commented on templates/default/views/DashboardView.html
> +              'selected': tc.id === currentTestCase.id
You could probably use one of the bootstrap classes for it.

2016-11-24 13:06 UTC, eger-geger commented on templates/default/views/DashboardView.html
> +            ng-repeat="tc in testCases | filter : testCaseFilter | filter: textFilter"
Please rename to _testCaseResultFilter_ and _testCaseTextFilter_

2016-11-25 09:34 UTC, AlexGalchenko commented on templates/default/views/DashboardView.html
> +               <label for="excludeFilter"><input type="checkbox" id="excludeFilter" ng-model="excludeFilter" ng-checked="excludeFilter"><code> Exclude</code></label>
changed to ng-attr-checked

2016-11-25 10:31 UTC, eger-geger commented on templates/default/js/controllers/DashboardController.js
> +	$scope.testCaseTextFilter = function(testCase) {
It does not filter by test case text but based on test status

2016-11-25 11:37 UTC, AlexGalchenko commented on templates/default/views/DashboardView.html
> +               <label for="excludeFilter"><input type="checkbox" id="excludeFilter" ng-model="excludeFilter" ng-checked="excludeFilter"><code> Exclude</code></label>
removed

2016-11-25 13:54 UTC, eger-geger approved these changes

2016-11-25 14:00 UTC, merged